baseURL: "https://inwardmovement.github.io/mettaconseil"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
disableKinds: ["taxonomy", "taxonomyTerm"]
params:
  description: "Psychanalyse"
  author: "Victor Massé"
author:
  name: "Victor Massé"
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  mainleft:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 2
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 3
    - Name: "Témoignages"
      URL: "/temoignages/"
      Identifier: "temoignages"
      weight: 4
