baseURL: "https://mettaconseil.fr"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en développement personnel"
  author: "Victor Massé"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 2
    # - Name: "Témoignages"
    #   URL: "/temoignages/"
    #   Identifier: "temoignages"
    #   weight: 3
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 4
  footer:
    - Name: "Mentions légales"
      URL: "/mentions-legales/"
      Identifier: "mentions-legales"
      weight: 1
    - Name: "GitHub"
      URL: "https://github.com/inwardmovement/mettaconseil/"
      Identifier: "github"
      weight: 2
    - Name: "Pour les professionnels"
      URL: "https://pro.mettaconseil.fr/"
      Identifier: "pour-les-particuliers"
      weight: 3
