baseURL: "https://mettaconseil.com"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en développement personnel"
  author: "Victor Massé"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 2
    # - Name: "Témoignages"
    #   URL: "/temoignages/"
    #   Identifier: "temoignages"
    #   weight: 3
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 4
  footer:
    - Name: "Mentions légales"
      URL: "/mentions-legales/"
      Identifier: "mentions-legales"
      weight: 1
