name: ci-cd-master

on:
  push:
    branches:
      - master

env:
  PRODUCTION: true
  HUGO_VERSION: '0.65.3'
  NODE_VERSION: '12.14.0'
  NETLIFY_SITE_ID: '27640b6d-7a50-4d72-bd59-1c22c4000662'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_METTACONSEIL }}

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-prod
      if: success()
